# Generated by Django 4.1.3 on 2023-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifications',
            options={'verbose_name': 'EmailVerification', 'verbose_name_plural': 'EmailVerifications'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
