# Generated by Django 4.1.5 on 2023-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
